FROM --platform=linux/amd64 python:3.12-slim-bookworm

ENV AM_I_IN_DOCKER_CONTAINER=Yes
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget curl ca-certificates gnupg locales sudo git openssh-client \
    jq libmagic1 tzdata netcat-openbsd procps && \
    rm -rf /var/lib/apt/lists/* && apt-get clean

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

ENV TZ=America/Toronto
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    dpkg-reconfigure -f noninteractive tzdata

RUN useradd miner -G sudo,www-data -s /bin/bash -m && \
    echo miner:12qw | chpasswd

USER miner
ENV HOME=/home/miner
WORKDIR $HOME

RUN python3 -m venv $HOME/venv
ENV VIRTUAL_ENV=$HOME/venv
ENV PATH="$VIRTUAL_ENV/bin:$HOME/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir uv

RUN mkdir -p $HOME/bin && \
    echo 'export PATH="$HOME/venv/bin:$HOME/bin:$PATH"' >> $HOME/.profile && \
    echo 'export VIRTUAL_ENV="$HOME/venv"' >> $HOME/.profile
