[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "browserscraper"
dynamic = ["version"]
description = "Browser Scraper for Miner"
license = "Apache-2.0"
requires-python = ">=3.12"
dependencies = [
    "mongoengine",
    "selenium",
    "webdriver-manager",
]

[tool.setuptools.dynamic]
version = { attr = "browserscraper._version.__version__" }

[tool.setuptools.packages.find]
include = ["browserscraper*"]
